### ISSUE TITLE
Not able to register for new Application 

### ISSUE THREAD

**Issue by shivam183** [gita/BhagavadGita#141]
I'm trying to register an application but after clicking Create Your Application, it just redirects me to the same page. I'm Registered and Email is verified

**Comment by samanyougarg** [comment]
Hi @shivam183 

Sorry for the late reply. 
I tried registering a new application and it worked just fine for me. 

Please let me know if you are still facing the error.

Radhe Radhe

**Comment by samanyougarg** [comment]
I am closing the issue. Please feel free to create a new one if you are still facing any problems.

**Comment by sanketn1990** [comment]
I having the same issue. I try to register a new app but it's just showing the same page again without any error message
