### ISSUE TITLE
Development Environment not running on windows

### ISSUE THREAD

**Issue by redraushan** [gita/BhagavadGita#227]
# What:
Not able to run project locally on windows, Followed the development guide mentioned at - [https://github.com/gita/BhagavadGita#developing-locally]()

# Why:
Throws `'foreman' is not recognized as an internal or external command, operable program or batch file.` while issuing the command `foreman start -f local` to start the server.

# Expected:
Local development server should run by issuing the command - `foreman start -f local`

Python version:  3.7.2
OS Name: Microsoft Windows 10 Enterprise
OS Version: N/A Build 17134

**Comment by samanyougarg** [comment]
Hi @redraushan,

I really appreciate your enthusiasm to the project and am sorry for the delay. Please find the updated instructions below.

1. Fork this repository and clone the forked repository.
2. Create and activate a Python 3 virtualenv.
3. Use `pip install -r requirements.txt` to install the requirements.
4. `python manage.py runserver` to start the server.
5. Create an environment file `config.env`. Please email contact@bhagavadgita.io for the credentials of the file.
6. API can be accessed at `http://127.0.0.1:5000/api/v1` and frontend can be accessed at `http://127.0.0.1:5000`.

Please let me know if you face any problems.

**Comment by redraushan** [comment]
Hi @samanyougarg,

Thanks for the help :), I am able to start the project, however the command `python manage.py runserver` is running the project in `production` mode, do we have any way to start the server in `development` mode?

Please find the logs below:

```bash
C:\code\BhagavadGita>python manage.py runserver
Importing environment from .env file
SECRET KEY ENV VAR NOT SET! SHOULD NOT SEE IN PRODUCTION
THIS APP IS IN DEBUG MODE. YOU SHOULD NOT SEE THIS IN PRODUCTION.
RadhaKrishnaHanuman
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
```

**Comment by samanyougarg** [comment]
Hi @redraushan,

Thank you for letting me know.

Please add the following to your config.env file  - 
`SECRET_KEY=Your_Secret_Key`
`FLASK_ENV=development`

This will run the server in dev mode.

**Comment by redraushan** [comment]
> Hi @redraushan,
> 
> Thank you for letting me know.
> 
> Please add the following to your config.env file -
> `SECRET_KEY=Your_Secret_Key`
> `FLASK_ENV=development`
> 
> This will run the server in dev mode.

Which SECRET_KEY we would need to use for development environment?

**Comment by samanyougarg** [comment]
You can use any string as your secret key.

**Comment by redraushan** [comment]
Thanks @samanyougarg for your support, I believe we can close the issue now.
