### ISSUE TITLE
Scroll to top icon is not clickable in ios safari

### ISSUE THREAD

**Issue by redraushan** [gita/BhagavadGita#232]
# What
1. Clicking scroll-to-top icon is not scrolling the page in ios safari browser, however the same functionality is working in chrome on ios.

2. The scroll-to-top icon is not getting clicked if the same is getting overlapped with any clickable content.

# Expected 
1.  Clicking scroll-to-top icon should work across the browser.
2.  The scroll-to-top icon should be always on top with greater z-index to make it clickable in case of overlapping.

**Comment by samanyougarg** [comment]
Hi @redraushan,

Thank you for reporting the issue.

Would you like to take on this issue?

Thanks
Sam

**Comment by redraushan** [comment]
Hi @samanyougarg,

I’m in the process of raising the PR, moreover in “Add to favourite” heart icon is a bit off, I will also fix the alignment part of this.

**Comment by samanyougarg** [comment]
Sure, that would be great. 
Please let me know when you submit the PR.
